version: '3.1'

services:

  db:
    container_name: support_system_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          - ./docker/sql-scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080